---
title: "JeffBostonDataWrangling"
author: "Jeff Fromuth"
date: "4/9/2022"
output: html_document
---

```{r}
#install.packages("tigris")
#install.packages("sf")
#install.packages("tidycensus")
library(tidyverse)
library(lubridate)
library(tigris)
library(mapview)
library(sf)
library(ggplot2)
library(tidycensus)
library(dplyr)
options(tigris_use_cache = TRUE)
```

##homeownership (absolute) 
```{r Homeownership absolute}

boston_HMO <- get_acs(
  geography = "tract", 
  variables = "B25118_002E",
  state = "25025", 
  county = "025",
  geometry = TRUE
)

plot(boston_HMO["estimate"]) 

filtered_allegheny_income <- transform(allegheny_income, CensusTract = substr(GEOID, 6, 9))

pittsburgh_income <- filtered_allegheny_income %>% 
      filter(CensusTract %in% tracts$X0103)


dc_income
plot(dc_income["estimate"])

```

##total homes (absolute) 
```{r Total homes absolute}

boston_Htot <- get_acs(
  geography = "tract", 
  variables = "B25118_001E",
  state = "25025", 
  county = "025",
  geometry = TRUE
  
)

```

#Mutate data and create percentages 
```{r mutate home data and plot}

bostonmerge <- cbind(boston_HMO,boston_Htot)

boston_HMOpr <- 
  bostonmerge %>% 
  filter(GEOID != "25025981202", GEOID != "25025981800", GEOID != "25025981300",
         GEOID != "25025990101", GEOID != "25025080801", 
         GEOID != "25025981100")%>%
  select(GEOID, NAME, variable, estimate, estimate.1, geometry) %>%
  mutate(percent = (estimate/estimate.1))
  
plot(boston_HMOpr["percent"])
```

```{r ggplot home data}

ggplot() + 
  geom_sf(data=boston_HMOpr, aes(fill=percent, geometry = geometry)) +
  scale_color_distiller(palette = "YlOrRd")

boston_HMOpr_sf <- boston_HMOpr %>% 
  st_as_sf(coords = c('SITE_LONGITUDE','SITE_LATITUDE'), crs=4269)
```


```{r selected map for cleaning}

bos_select1 <-
  boston_HMOpr %>%
  filter(GEOID == "25025120103"| GEOID == "25025130100"| GEOID == "25025130402"| GEOID == "25025110301"| GEOID == "25025140105")

plot(bos_select1["percent"])
```

